package hibernateController;

import hibernateDAO.AddhaarDAO;
import hibernateDAO.PersonDAO;
import hibernateDTO.Addhaar;
import hibernateDTO.Person;

public class AutoGeneratedId {

	public static void main(String[] args) 
	{
		Addhaar setAddhaar=new Addhaar();
		setAddhaar.setAddharPhNo(9003022960l);
		setAddhaar.setAddharAddress("51 tkm road mamallapuram");
		
		Person setPerson=new Person();
		setPerson.setpName("surya");
		setPerson.setpEmail("suriya1506@gmail");
		setPerson.setAddhaar(setAddhaar);
		
		PersonDAO sendperson=new PersonDAO();
		AddhaarDAO deleteAddhaar=new AddhaarDAO();
		deleteAddhaar.insertAddhaar(setAddhaar);
		sendperson.insertPerson(setPerson);
		
//		here 
		Person findedPerson = sendperson.findPerson(1);
		Addhaar addhaar = findedPerson.getAddhaar();
		findedPerson.setAddhaar(null);
		Person updatedPerson = sendperson.updatePerson(findedPerson, 1);
		deleteAddhaar.deleteAddhaar(addhaar.getAddharNumber());
		System.out.println(updatedPerson);		
		
	}

}
